### ISSUE TITLE
tnyga script is broken

### ISSUE THREAD

**Issue by Tigerwolfy** [iantrich/ChrUbuntu-Guides#11]
The tnyga script guide states in step 13 to run the script a second time using : curl -L -O http://goo.gl/<script_name>; sudo bash <script_name> -m <ubuntu_flavor> -u <version> -a <architecture>
However the script itself looks first at $1 and if not blank, defines and uses $1 as ${target disk}, but if blank uses target disk="`rootdef -d -s`".   Therefore the second run thinks "-m" is the target drive.  The other arguments to the script (including -h for help) are never examined or used, making selection of any options impossible.

Also, Google now is push-updating (at least C-710 Parrot) to a 3.8.11 kernel, which so far, I've been unable to get to successfuly install X/Ubuntu with either tnyga or s9ryd scripts.  S9ryd loads the OS and Xubuntu-desktop, but on reboot, screen goes and remains black.  Using a old 32-bit 'recovery USB' to go back to the 'seashore fjord wallpaper' version that installs a 3.4.0 kernel, you can install 12.04-32 bit, then upgrade, but a dist-upgrade to 14.04-32 bit (or 64 bit with tnyga) version needs at least a 3.6 kernel for 'mesa' video drivers in 14.04 to work with many programs like abiword and many screensavers because of the old kernel.

Please look into the these issues.  I have 35 C-710 machines routinely used in emergency shelters and several conventions that need to have updates to supported Xubuntu releases.

**Comment by iantrich** [comment]
Hey,

Unfortunately our guides are merely for reference and their is no ongoing development on the ChrUbuntu project since the sole developer abandoned the project. I would suggest using ROMs provided by John Lewis, www.johnlewis.ie for ongoing stability as they provide a pure seabios system to install from.

**Comment by srinathh** [comment]
The other option you could look at is [Crouton](https://github.com/dnschneid/crouton) which lets you run various flavors of ubuntu & debian in a chroot within ChromeOS itself. The main advantage of the crouton approach is essentially that all the hardware drivers are provided by ChromeOS itself - so you're less likely to run into hardware issues. The project is also actively maintained. 

The disadvantage of that kind of a setup is primarily that you'll have to do some [fancy gymnastics](https://docs.google.com/document/d/1WQnfloMbcR798Lk-iYPbvZt-wplW83IYyCf7SYyXTvs/edit) if you want to run kernel modules like KVM. However, i'm guessing this is a really niche use-case (In my case, I'm using the ChromeBook as a dev machine & running both Windows & Android Emulator via KVM) 

I move my Chromebook from ChrUbuntu to Crouton some months back primarily for stability reasons.

**Comment by nh2** [comment]
See https://github.com/iantrich/ChrUbuntu-Guides/issues/25#issuecomment-483914297

**Comment by nh2** [comment]
I've also backed them up at https://github.com/nh2/ChrUbuntu
