### ISSUE TITLE
Screwed my laptop

### ISSUE THREAD

**Issue by DHunter3** [iantrich/ChrUbuntu-Guides#17]
Acer c720. everything was working fine and then my screen went white for awhile. i pressed esc+refresh+power and the "chrome os is broken" screen popped up i turned it off and back on and tried ctrl+l but that turned the screen black. restarted, went back into developer mode, saw that i was missing 9gb, turned off dev. mode, power washed, turned back on dev. mode, still missing. is there a command so i can remove this?

**Comment by iantrich** [comment]
Unfortunately you'll need to turn off Dec mode and then do a full chrome OS recovery

**Comment by DHunter3** [comment]
as in download an image onto an external and put it onto my chromebook right? just want to clarify before i do anything. im not meaning to sound like a jackass it just really irritated me last night

**Comment by iantrich** [comment]
Yeah, I can't point to the reason as to why it happened in the first place, but since you already tried to powerwash you'll need to do a system recovery. I don't know of anyway to get the partition back. Put this on a USB and install: https://support.google.com/chromebook/answer/1080595?hl=en
