### ISSUE TITLE
I installed ChrUbuntu on my samsung chrombook series 3

### ISSUE THREAD

**Issue by Gatluak** [iantrich/ChrUbuntu-Guides#21]
After it boot to boot to chromeOS, i followed the procedures and went to the virtual terminal 2. but it denies the semicolons when i type this command, curl -L -O http://goo.gl/<tnyga>;sudo bash <tnyga> -h and brings this error , -bash: syntax error near unexpected token ';'

**Comment by iantrich** [comment]
Hey @Gatluak, ChrUbuntu isn't a viable solution anymore from Chromebooks. I would look into some of the currently supported projects:
[Gallium OS](https://www.reddit.com/r/GalliumOS)
[ChrUltrabook (Windows 10)](https://www.reddit.com/r/ChrUltrabook)
[Crouton](https://www.reddit.com/r/Crouton)
[chrx](https://github.com/reynhout/chrx)

**Comment by Gatluak** [comment]
hi Ian
I tried the crouton and it is my third day and haven't personalized it well
so far. I am a student of electronics engineering so naturally I need to
use it for engineering software and programming. Thanks for your
recommendations about GalliumOS and ChrUltrabook,let me look into them and
come up with the one that impresses me.

**Comment by iantrich** [comment]
I ran Mint using John Lewis firmware on my Chromebook throughout my computer engineering degree; it worked out great.

https://johnlewis.ie/
