### ISSUE TITLE
chromebook pixel 2013 link

### ISSUE THREAD

**Issue by alvesadrian** [iantrich/ChrUbuntu-Guides#22]
which one i need to use for a chromebook pixel 2013 link model:
tnyga or 9sgchs ??

Thanks Adrian.-

**Comment by iantrich** [comment]
ChrUbuntu is no longer recommended and most likely will no longer work on any models that have up to date firmware. I suggest checking out on of the following:

Chrx
John Lewis coreboot Firmware
/r/ChromeOS
/r/Crouton (Ubuntu in ChromeOS)
/r/ChrUltrabook (Windows 10 on Chromebook)
/r/GalliumOS
