### ISSUE TITLE
goo.gl links are dead

### ISSUE THREAD

**Issue by kenorb** [iantrich/ChrUbuntu-Guides#25]
Links mentioned in the [Installing ChrUbuntu.md](https://github.com/iantrich/ChrUbuntu-Guides/blob/master/Guides/Installing%20ChrUbuntu.md) are dead.

- http://goo.gl/tnyga
- http://goo.gl/9sgchs

**Comment by iantrich** [comment]
ChrUbuntu is no longer maintained and neither are these guides. Recommend checking out Gallium OS or Crouton

**Comment by nh2** [comment]
Luckily archive.org has them:

* [tynga](https://web.archive.org/web/20160721142151/http://cr-48-ubuntu.googlecode.com/files/install-ubuntu-1204-9.sh)
* [9sgchs](https://web.archive.org/web/20140513010922/https://googledrive.com/host/0B0YvUuHHn3MndlNDbXhPRlB2eFE/chrubuntu-seabios-install.txt)
