### ISSUE TITLE
Lenovo n20p: ChrUbuntu on external USB

### ISSUE THREAD

**Issue by gdm85** [iantrich/ChrUbuntu-Guides#3]
I have followed Guides/Installing ChrUbuntu.md for a Lenovo n20p; aside from the first login (that had already been done, but I rebooted to access VT2), I followed everything precisely to install on an USB stick.

I installed with `sudo sh 9sgchs -m ubuntu-minimal -t /dev/sda 0u lts`.

I noticed some errors due to parted not existing as a binary in my ChromeOS (firmware Google_Clapper.5216.199.7, platform 6812.88.0 stable-channel clapper).

At reboot, I tried both Ctrl+L and the OS-advised Ctrl+U, I get in first case a double beep and in second a single beep. The same happens if I unplug the USB stick, and no matter which type of USB I am using (there is 1 USB2 and 1 USB3 port).

Any tip/idea? Shall we add an issue for this laptop?

**Comment by gdm85** [comment]
It turns out that if the USB device is:

```
New USB device found, idVendor=058f, idProduct=6387
```

Then the bootloader will not see it at all!

Is it worth mentioning somewhere?

**Comment by iantrich** [comment]
Very strange. Want to make a pull request and add it to https://github.com/iantrich/ChrUbuntu-Guides/blob/master/Issues/N20P

**Comment by gdm85** [comment]
@iantrich it's a problem that affects many models of chromebooks, basically there are type of USB sticks that the bootloader won't see at all.

https://code.google.com/p/chromium/issues/detail?id=386314
https://code.google.com/p/chromium/issues/detail?id=466758

Do you want a PR that mentions these?

**Comment by iantrich** [comment]
That would be awesome, tahnks @gdm85 !
