### ISSUE TITLE
rejects and already applied patches

### ISSUE THREAD

**Issue by bbigras** [iantrich/ChrUbuntu-Guides#5]
Asys C200
9sgchs
ubuntu-desktop
latest
amd64

![image](https://cloud.githubusercontent.com/assets/24027/8298038/7a4b3998-1931-11e5-9873-33f451e4cec3.png)

**Comment by iantrich** [comment]
The Asus C200 is known to not work with ChrUbuntu. We're working on getting a better list of compatible hardware in the guides. Crouton is recommended for now.
